name: Anime-Kanri-build
on: ['push']
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flutter-actions/setup-flutter@v2
      - name: Setup-environment
        run: |
          Import-Module "$env:ChocolateyInstall/helpers/chocolateyInstaller.psm1"
          choco install protoc
          cargo install rinf
          flutter upgrade
          refreshenv
      - name: Build-Windows
        run: |
          flutter pub get
          rinf message
          flutter build windows --release
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flutter-actions/setup-flutter@v2
      - name: Setup-environment
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libgtk-3-dev ninja-build
          yes | flutter doctor --android-licenses
          cargo install rinf
          flutter upgrade
          protoc --version
      - name: Build-Linux
        run: |
          flutter pub get
          rinf message
          flutter build linux --release
          flutter build apk --release
