name: Anime-Kanri-build
on: ['push']
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flutter-actions/setup-flutter@v2
      - name: Setup-environment
        run: |
          Import-Module "$env:ChocolateyInstall/helpers/chocolateyInstaller.psm1"
          choco install protoc
          cargo install rinf
          flutter upgrade
          refreshenv
      - name: Build-Windows
        run: |
          flutter pub get
          rinf message
          flutter build windows --release
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flutter-actions/setup-flutter@v2
      - name: Setup-environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev ninja-build libssl-dev
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
          unzip protoc-3.15.8-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
          yes | flutter doctor --android-licenses
          cargo install rinf
          flutter upgrade
      - name: Build-Linux
        run: |
          flutter pub get
          rinf message
          flutter build linux --release
          flutter build apk --release
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flutter-actions/setup-flutter@v2
      - name: Setup-environment
        run: |
          brew install protobuf
          cargo install rinf
          flutter upgrade
      - name: Build-Macos
        run: |
          flutter pub get
          rinf message
          flutter build macos --release
